# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'todolist.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(540, 458)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.additemlineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.additemlineEdit.setGeometry(QtCore.QRect(30, 30, 471, 41))
        self.additemlineEdit.setObjectName("additemlineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda:self.add_it())
        self.pushButton.setGeometry(QtCore.QRect(40, 100, 131, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda:self.delete_it())
        self.pushButton_2.setGeometry(QtCore.QRect(210, 100, 121, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda:self.clear_it())
        self.pushButton_3.setGeometry(QtCore.QRect(370, 100, 121, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.mylist_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.mylist_listWidget.setGeometry(QtCore.QRect(30, 170, 471, 211))
        self.mylist_listWidget.setObjectName("mylist_listWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 540, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def add_it(self):
        #grab item from the list
        item= self.additemlineEdit.text()
        
        #add item to the list
        self.mylist_listWidget.addItem(item)

        #clear the item box
        self.additemlineEdit.setText("")
    def delete_it(self):
        #grab the selected row
        clicked= self.mylist_listWidget.currentRow()
        #self.additemlineEdit.setText(str(clicked))
        #delete selected row
        self.mylist_listWidget.takeItem(clicked)
    def clear_it(self):    
        self.mylist_listWidget.clear()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TO DO LIST "))
        self.pushButton.setText(_translate("MainWindow", "Add Item to the list"))
        self.pushButton_2.setText(_translate("MainWindow", "Delete Item from list"))
        self.pushButton_3.setText(_translate("MainWindow", "Clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
